name: CI

on:
  push:

permissions:
  id-token: write

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up python
          id: setup-python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Install and configure Poetry
          uses: snok/install-poetry@v1
        - name: Run tests
          run: |
            poetry install
            poetry run pytest
          env:
            API_TOKEN: ${{ secrets.API_TOKEN }}
            API_USER: ${{ secrets.API_USER }}
        - name: Build the package
          run: poetry build
        - name: Publish the package
          if: github.ref == 'refs/tags/*'
          uses: pypa/gh-action-pypi-publish@release/v1